"""empty message

Revision ID: 8314e1f7962e
Revises: 
Create Date: 2023-02-10 20:13:11.987572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8314e1f7962e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkmateuser',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('jtw', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('med',
    sa.Column('med_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('med_name', sa.String(), nullable=True),
    sa.Column('rxcui', sa.String(), nullable=True),
    sa.Column('dose', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('checkmateuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checkmateuser_id'], ['checkmateuser.user_id'], ),
    sa.PrimaryKeyConstraint('med_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('med')
    op.drop_table('checkmateuser')
    # ### end Alembic commands ###
