"""empty message

Revision ID: efb3063bdf02
Revises: 8314e1f7962e
Create Date: 2023-02-13 16:20:08.971612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb3063bdf02'
down_revision = '8314e1f7962e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkmateuser', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkmateuser', 'picture')
    # ### end Alembic commands ###
